name: Go Build
on: [push]
env:
  GO111MODULE: on
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        go: ["1.12.x", "1.13.x"]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{matrix.go}}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Installing additional dependencies
        run: |
          go get github.com/modocache/gover;
          go get github.com/mattn/goveralls;
          go get golang.org/x/tools/cmd/cover;
          go get golang.org/x/tools/cmd/goimports;
          go get github.com/stretchr/testify/assert;

      - name: Lint code
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
          go get golang.org/x/tools/cmd/goimports;
          go get -u golang.org/x/lint/golint 

          gofiles=$(find ./ -name '*.go') && [ -z "$gofiles" ] || unformatted=$(goimports -l $gofiles) && [ -z "$unformatted" ] || (echo >&2 "Go files must be formatted with gofmt. Following files has problem: $unformatted" &&  false);
          COMMENT=$(diff <(echo -n) <(gofmt -s -d .))
          GITHUB_TOKEN=${{secrets.github_token}}
          PAYLOAD=$(echo '{}' | jq --arg body "$COMMENT" '.body = $body')
          COMMENTS_URL=$(cat /github/workflow/event.json | jq -r .pull_request.comments_url)
          if [ "COMMENTS_URL" != null ]; then
            curl -s -S -H "Authorization: token $GITHUB_TOKEN" --header "Content-Type: application/json" --data "$PAYLOAD" "$COMMENTS_URL" > /dev/null
          fi


          golint ./...

      - name: Static code check
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -u github.com/gordonklaus/ineffassign
          ineffassign .
          go vet ./...

      - name: Test
        run: |
          go test -race -count=1 -coverprofile=queue.coverprofile ./queue
          go test -race -count=1 -coverprofile=server.coverprofile  ./server
          go test -race -count=1 -coverprofile=main.coverprofile

      - name: Upload coverage to codecov
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/
          go get github.com/modocache/gover;
          echo "" > coverage.txt
          gover
          cat gover.coverprofile >> coverage.txt
          bash <(curl -s https://codecov.io/bash)

      # - name: Coveralls upload
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.github_token }}
      #     path-to-lcov: ./gover.coverprofile

      - name: Build
        run: go build -v .
